version: '2.0'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass258
      - POSTGRES_DB=django_db
volumes:
  postgres_data:
