# Generated by Django 2.2.12 on 2020-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=32)),
                ('ptype', models.CharField(choices=[('BND', 'Bond'), ('EQY', 'Equity'), ('ETF', 'ETF'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('assetclass', models.CharField(choices=[('EQS', 'Equities'), ('FXI', 'Fixed Income'), ('CSH', 'Cash'), ('ALT', 'Alternatives')], default='ALT', max_length=3)),
                ('info', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
